defaults:
  - model: qwen
  - dataset: 2wiki
  - search: default
  - _self_

resources:
  global_llm_concurrency: 24
  global_gpu_concurrency: 1

storage:
  path: ${hydra:runtime.cwd}/storage/${dataset.name}

output_dir: ${hydra:runtime.cwd}/outputs/${dataset.name}
